spring:
  h2:
    console:
      enabled: true
  datasource:
    initialization-mode: always
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none # TODO 2-4 ddl-auto (schema.sql 이 없어도 될까?)
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: myNeighborhood.model
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8081

