spring:
  h2:
    console:
      enabled: true
  datasource:
    initialization-mode: always
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: myNeighborhood.model
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8081
